"""initial_schema

Revision ID: 95ad520236a3
Revises: 
Create Date: 2026-06-10 06:39:37.482913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ad520236a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('payload_sha256', sa.String(length=64), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_sequence_no'), 'audit_log', ['sequence_no'], unique=True)
    op.create_table('commission_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_no', sa.String(length=64), nullable=False),
    sa.Column('claim_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_claims_idempotency_key'), 'commission_claims', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_commission_claims_policy_no'), 'commission_claims', ['policy_no'], unique=False)
    op.create_index('uq_commission_claims_active', 'commission_claims', ['policy_no', 'reason_code'], unique=True, postgresql_where=sa.text("status <> 'closed'"), sqlite_where=sa.text("status <> 'closed'"))
    op.create_table('crm_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_no', sa.String(length=64), nullable=False),
    sa.Column('recorded_commission', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('recorded_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_records_policy_no'), 'crm_records', ['policy_no'], unique=False)
    op.create_table('dealers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('oem', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escalations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_no', sa.String(length=64), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('escalation_reason', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('finding_context', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_policy_no'), 'escalations', ['policy_no'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('policy_no', sa.String(length=64), nullable=False),
    sa.Column('insurer', sa.String(length=128), nullable=True),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('detector', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recon_status', sa.String(length=32), nullable=True),
    sa.Column('resolution_state', sa.String(length=32), nullable=True),
    sa.Column('disposition', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_policy_no'), 'findings', ['policy_no'], unique=False)
    op.create_index(op.f('ix_findings_run_id'), 'findings', ['run_id'], unique=False)
    op.create_table('insurer_commission_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insurer_name', sa.String(length=128), nullable=True),
    sa.Column('raw_policy_ref', sa.String(length=128), nullable=True),
    sa.Column('commission_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('policy_no', sa.String(length=64), nullable=True),
    sa.Column('premium', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(length=32), nullable=True),
    sa.Column('normalization_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurer_commission_feeds_insurer_name'), 'insurer_commission_feeds', ['insurer_name'], unique=False)
    op.create_index(op.f('ix_insurer_commission_feeds_policy_no'), 'insurer_commission_feeds', ['policy_no'], unique=False)
    op.create_index(op.f('ix_insurer_commission_feeds_raw_policy_ref'), 'insurer_commission_feeds', ['raw_policy_ref'], unique=False)
    op.create_table('reconciliation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_no', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('expected', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('delta', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolution_state', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_results_policy_no'), 'reconciliation_results', ['policy_no'], unique=False)
    op.create_index(op.f('ix_reconciliation_results_reason_code'), 'reconciliation_results', ['reason_code'], unique=False)
    op.create_index(op.f('ix_reconciliation_results_resolution_state'), 'reconciliation_results', ['resolution_state'], unique=False)
    op.create_index(op.f('ix_reconciliation_results_status'), 'reconciliation_results', ['status'], unique=False)
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('vehicle_reg', sa.String(length=32), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('rsa_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('renewal_1plus1_eligible', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('renewal_provisioned', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_rsa_subscription_id'), 'sales', ['rsa_subscription_id'], unique=False)
    op.create_index(op.f('ix_sales_vehicle_reg'), 'sales', ['vehicle_reg'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insurer_name', sa.String(length=128), nullable=False),
    sa.Column('policy_no', sa.String(length=64), nullable=False),
    sa.Column('premium', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_commission_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_no')
    )
    op.create_index(op.f('ix_policies_insurer_name'), 'policies', ['insurer_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policies_insurer_name'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_sales_vehicle_reg'), table_name='sales')
    op.drop_index(op.f('ix_sales_rsa_subscription_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('reconciliation_runs')
    op.drop_index(op.f('ix_reconciliation_results_status'), table_name='reconciliation_results')
    op.drop_index(op.f('ix_reconciliation_results_resolution_state'), table_name='reconciliation_results')
    op.drop_index(op.f('ix_reconciliation_results_reason_code'), table_name='reconciliation_results')
    op.drop_index(op.f('ix_reconciliation_results_policy_no'), table_name='reconciliation_results')
    op.drop_table('reconciliation_results')
    op.drop_index(op.f('ix_insurer_commission_feeds_raw_policy_ref'), table_name='insurer_commission_feeds')
    op.drop_index(op.f('ix_insurer_commission_feeds_policy_no'), table_name='insurer_commission_feeds')
    op.drop_index(op.f('ix_insurer_commission_feeds_insurer_name'), table_name='insurer_commission_feeds')
    op.drop_table('insurer_commission_feeds')
    op.drop_index(op.f('ix_findings_run_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_policy_no'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_escalations_policy_no'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_table('dealers')
    op.drop_index(op.f('ix_crm_records_policy_no'), table_name='crm_records')
    op.drop_table('crm_records')
    op.drop_index('uq_commission_claims_active', table_name='commission_claims', postgresql_where=sa.text("status <> 'closed'"), sqlite_where=sa.text("status <> 'closed'"))
    op.drop_index(op.f('ix_commission_claims_policy_no'), table_name='commission_claims')
    op.drop_index(op.f('ix_commission_claims_idempotency_key'), table_name='commission_claims')
    op.drop_table('commission_claims')
    op.drop_index(op.f('ix_audit_log_sequence_no'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
