"""add_user_management_fields

Revision ID: d2781d8164a4
Revises: 95ad520236a3
Create Date: 2026-06-10 12:52:34.831997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2781d8164a4'
down_revision: Union[str, Sequence[str], None] = '95ad520236a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'must_change_password')
    # ### end Alembic commands ###
